# Generated by Django 2.0.2 on 2018-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180329_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance_stock',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='book_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='book_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='copies_printed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='copies_sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='royalty_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='royalty_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specimen_issued',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_copies',
            field=models.IntegerField(null=True),
        ),
    ]
